[package]
name = "moar-horse"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "2.2.1"

[lib]
crate-type = ["cdylib", "lib"]
